DROP TABLE COF_TRANSACCION ;

DROP TABLE COF_MOVIMIENTO ;

DROP TABLE COF_MOVIMIENTO_TMP ;

DROP TABLE COF_SALDO_INICIAL ;

DROP TABLE COF_MAYOR ;

DROP TABLE COF_CUENTA_ESTANDAR ;

DROP TABLE COF_CUENTA_ESTANDAR_HIST ;

DROP TABLE COF_CUENTA ;

DROP TABLE COF_CUENTA_HIST ;

DROP TABLE COF_MAYOR_AUXILIAR ;

DROP TABLE COF_CUENTA_AUXILIAR ;

DROP TABLE COF_ATTR_CUENTA_AUXILIAR ;

DROP TABLE COF_SECTOR ;

DROP TABLE COF_MAPEO_AREA ;

DROP TABLE COF_MAPEO_SECTOR ;

DROP TABLE COF_MAPEO_MONEDA ;

DROP TABLE COF_MAPEO_MAYOR_AUXILIAR ;

DROP TABLE COF_GRUPO_MAYOR ;

DROP TABLE COF_ELEMENTO_GRUPO_MAYOR ;

DROP TABLE COF_AGRUPACION ;

DROP TABLE COF_REGLA_AGRUPACION ;

DROP TABLE COF_REGLA_CONTABLE ;

DROP TABLE COF_EMPRESA ;

DROP TABLE COF_DOMICILIO ;

DROP TABLE AO_CALENDARS ;

DROP TABLE AO_HOLIDAYS ;

DROP TABLE AO_NOT_LABOR_WEEKDAYS ;

DROP TABLE AO_PERIODS ;

DROP TABLE AO_CURRENCIES ;

DROP TABLE AO_EXCHANGE_RATES ;

DROP TABLE AO_ENTITIES ;

DROP TABLE AO_ENTITY_ATTRIBUTES ;

DROP TABLE AO_ENTITY_ATTR_DEF ;

DROP TABLE AO_ATTR_DEF ;

DROP TABLE AO_SET_ITEMS ;

DROP TABLE AO_OBJECTS ; 

DROP TABLE AO_TREES ; 

DROP TABLE MH_PARTICIPANTS ;

DROP TABLE MH_PARTICIPANT_OBJECTS ;

DROP TABLE MH_TASKS ;

DROP TABLE MH_USERS ;

/* *********************** ELIMINACIÓN DE TABLAS TEMPORALES ************************* */

DROP TABLE TMP_ABONOSPERIODTBL ;

DROP TABLE TMP_ABONOSTBL ;

DROP TABLE TMP_CARGOSPERIODTBL ;

DROP TABLE TMP_CARGOSTBL ;

DROP TABLE TMP_MOVSTBL ;

DROP TABLE TMP_SALDOSINICIALESTBL ;

DROP TABLE TMP_SI_TBL ;

DROP TABLE TMP_TOTABONOSSUMPERTBL ;

DROP TABLE TMP_TOTABONOSTBL ;

DROP TABLE TMP_TOTCARGOSSUMPERTBL ;

DROP TABLE TMP_TOTCARGOSTBL ;

DROP TABLE TMP_TOTSI_TBL ;

DROP TABLE TMP_SALDOS ;

DROP TABLE TMP_SALDOS_EXT ;