DROP SEQUENCE SEC_ID_TRANSACCION ;

DROP SEQUENCE SEC_ID_MOVIMIENTO_TMP ;

DROP SEQUENCE SEC_ID_SALDO_INICIAL ;

DROP SEQUENCE SEC_ID_MAYOR ;

DROP SEQUENCE SEC_ID_CUENTA_ESTANDAR ;

DROP SEQUENCE SEC_ID_CUENTA_ESTANDAR_HIST ;

DROP SEQUENCE SEC_ID_CUENTA ;

DROP SEQUENCE SEC_ID_CUENTA_HIST ;

DROP SEQUENCE SEC_ID_MAYOR_AUXILIAR ;

DROP SEQUENCE SEC_ID_CUENTA_AUXILIAR ;

DROP SEQUENCE SEC_ID_ATTR_CUENTA_AUXILIAR ;

DROP SEQUENCE SEC_ID_SECTOR ;

DROP SEQUENCE SEC_ID_GRUPO_MAYOR ;

DROP SEQUENCE SEC_ID_ELEMENTO_GRUPO_MAYOR ;

DROP SEQUENCE SEC_ID_AGRUPACION ;

DROP SEQUENCE SEC_ID_REGLA_AGRUPACION ;

DROP SEQUENCE SEC_ID_EMPRESA ;

DROP SEQUENCE SEC_ID_DOMICILIO ;

DROP SEQUENCE SEC_CALENDAR_ID ;

DROP SEQUENCE SEC_HOLIDAY_ID ;

DROP SEQUENCE SEC_PERIOD_ID ;

DROP SEQUENCE SEC_CURRENCY_ID ;

DROP SEQUENCE SEC_EXCHANGE_RATE_ID ;

DROP SEQUENCE SEC_ENTITY_ID ;

DROP SEQUENCE SEC_ENTITY_ATTRIBUTE_ID ; 

DROP SEQUENCE SEC_ENTITY_ATTR_DEF_ID ;

DROP SEQUENCE SEC_ATTR_DEF_ID ;

DROP SEQUENCE SEC_SET_ITEM_ID ;

DROP SEQUENCE SEC_OBJECT_ID ;

DROP SEQUENCE SEC_NODE_ID ;

DROP SEQUENCE SEC_PARTICIPANT_ID ;

DROP SEQUENCE SEC_PARTICIPANT_OBJECT_ID ;

DROP SEQUENCE SEC_TASK_ID ;
