
DROP TABLE TMP_ABONOSPERIODTBL ;

DROP TABLE TMP_ABONOSTBL ;

DROP TABLE TMP_CARGOSPERIODTBL ;

DROP TABLE  TMP_CARGOSTBL ;

DROP TABLE TMP_MOVSTBL ;

DROP TABLE TMP_SALDOSINICIALESTBL ;

DROP TABLE TMP_SI_TBL ;

DROP TABLE TMP_TOTABONOSSUMPERTBL ;

DROP TABLE TMP_TOTABONOSTBL ;

DROP TABLE TMP_TOTCARGOSSUMPERTBL ;

DROP TABLE TMP_TOTCARGOSTBL ;

DROP TABLE TMP_TOTSI_TBL ;

DROP TABLE TMP_SALDOS ;

DROP TABLE TMP_SALDOS_EXT ; 
