/*  Tablas eliminadas pertencientes a la versión 1.0  */

CREATE TABLE COF_CUENTA
(
 ID_CUENTA			NUMBER(12) PRIMARY KEY,
 ID_MAYOR			NUMBER(12) NOT NULL ,
 ID_CUENTA_ESTANDAR		NUMBER(12) NOT NULL
);

CREATE TABLE COF_TRANSACCION
(
 ID_TRANSACCION			NUMBER(12) PRIMARY KEY ,
 NUMERO_TRANSACCION		VARCHAR2(16) ,
 ID_MAYOR			NUMBER(12) NOT NULL ,
 ID_FUENTE			NUMBER(12) NOT NULL ,
 ID_TIPO_TRANSACCION		NUMBER(12) NOT NULL ,
 ID_TIPO_POLIZA			NUMBER(12) NOT NULL ,
 CONCEPTO_TRANSACCION		VARCHAR2(1024) ,
 FECHA_AFECTACION		DATE NOT NULL ,
 FECHA_ELABORACION		DATE NOT NULL ,
 ID_ELABORADA_POR		NUMBER(12) NOT NULL ,
 ID_AUTORIZADA_POR		NUMBER(12) ,
 ESTA_ABIERTA			NUMBER(1) NOT NULL
);

CREATE TABLE COF_MOVIMIENTO
(
 ID_MOVIMIENTO			NUMBER(12) PRIMARY KEY ,
 ID_TRANSACCION			NUMBER(12) NOT NULL ,
 ID_CUENTA_ESTANDAR		NUMBER(12) NOT NULL ,
 ID_CUENTA_AUXILIAR		NUMBER(12) NOT NULL ,
 ID_SECTOR			NUMBER(12) NOT NULL ,
 ID_MOVIMIENTO_REFERENCIA	NUMBER(12) NOT NULL ,
 ID_AREA_RESPONSABILIDAD	NUMBER(12) NOT NULL ,
 CLAVE_PRESUPUESTAL		VARCHAR2(6) ,
 CLAVE_DISPONIBILIDAD		VARCHAR2(1) ,
 NUMERO_VERIFICACION		VARCHAR2(6) ,
 TIPO_MOVIMIENTO 		CHAR(1) NOT NULL ,
 FECHA_MOVIMIENTO		DATE ,
 CONCEPTO_MOVIMIENTO		VARCHAR2(255) ,
 ID_MONEDA			NUMBER(12) NOT NULL ,
 MONTO				NUMBER(25,10) NOT NULL ,
 MONTO_MONEDA_BASE		NUMBER(25,10) NOT NULL
);

CREATE TABLE COF_MOVIMIENTO_TMP
(
 ID_MOVIMIENTO_TMP		NUMBER(12) PRIMARY KEY , 
 ID_TRANSACCION			NUMBER(12) NOT NULL ,
 ID_CUENTA_ESTANDAR		NUMBER(12) NOT NULL ,
 ID_CUENTA_AUXILIAR		NUMBER(12) NOT NULL ,
 ID_SECTOR			NUMBER(12) NOT NULL , 
 ID_MOVIMIENTO_REFERENCIA	NUMBER(12) NOT NULL ,
 ID_AREA_RESPONSABILIDAD	NUMBER(12) NOT NULL ,
 CLAVE_PRESUPUESTAL		VARCHAR2(6) ,
 CLAVE_DISPONIBILIDAD		VARCHAR2(1) ,
 NUMERO_VERIFICACION		VARCHAR2(6) ,
 TIPO_MOVIMIENTO 		CHAR(1) NOT NULL ,
 FECHA_MOVIMIENTO		DATE ,
 CONCEPTO_MOVIMIENTO		VARCHAR2(255) ,
 ID_MONEDA			NUMBER(12) NOT NULL ,
 MONTO				NUMBER(25,10) NOT NULL ,
 MONTO_MONEDA_BASE		NUMBER(25,10) NOT NULL , 
 PROTEGIDO			NUMBER(1) NOT NULL
);


CREATE TABLE COF_SALDO_INICIAL
(
 ID_SALDO_INICIAL		NUMBER(12) PRIMARY KEY ,
 ID_MAYOR			NUMBER(12) NOT NULL , 
 ID_CUENTA_ESTANDAR		NUMBER(12) NOT NULL , 
 ID_CUENTA_AUXILIAR		NUMBER(12) NOT NULL , 
 ID_SECTOR			NUMBER(12) NOT NULL , 
 ID_MONEDA			NUMBER(12) NOT NULL , 
 FECHA_SALDO_INICIAL		DATE NOT NULL , 
 SALDO_INICIAL			NUMBER(25,10) NOT NULL
);


CREATE TABLE COF_MAYOR
(
 ID_MAYOR			NUMBER(12) PRIMARY KEY , 
 NOMBRE_MAYOR			VARCHAR2(512) NOT NULL , 
 NUMERO_MAYOR			VARCHAR2(6) , 
 SUB_NUMERO_MAYOR		VARCHAR2(6) , 
 PREFIJO_CUENTAS_AUXILIARES     VARCHAR2(16) , 
 ID_TIPO_CUENTAS_STD		NUMBER(12) NOT NULL , 
 ID_MONEDA_BASE			NUMBER(12) NOT NULL , 
 ID_EMPRESA			NUMBER(12) , 
 ID_CALENDARIO			NUMBER(12) NOT NULL , 
 FECHA_APERTURA			DATE NOT NULL , 
 FECHA_CIERRE			DATE , 
 ELIMINADO                      NUMBER(1) NOT NULL
); 


CREATE TABLE COF_CUENTA_ESTANDAR
(
 ID_CUENTA_ESTANDAR		NUMBER(12) PRIMARY KEY ,
 ID_TIPO_CUENTAS_STD		NUMBER(12) NOT NULL , 
 NUMERO_CUENTA_ESTANDAR		VARCHAR2(256) NOT NULL , 
 NOMBRE_CUENTA_ESTANDAR		VARCHAR2(256) NOT NULL , 
 DESCRIPCION			VARCHAR2(1024) , 
 ROL_CUENTA			CHAR(1) NOT NULL , 
 ID_TIPO_CUENTA			NUMBER(12) , 
 NATURALEZA			CHAR(1) 
);


CREATE TABLE COF_CUENTA_ESTANDAR_HIST
(
 ID_CUENTA_ESTANDAR_HIST	NUMBER(12) PRIMARY KEY ,
 ID_CUENTA_ESTANDAR		NUMBER(12) NOT NULL ,
 ID_TIPO_CUENTAS_STD		NUMBER(12) NOT NULL ,
 NUMERO_CUENTA_ESTANDAR		VARCHAR2(256) NOT NULL ,
 NOMBRE_CUENTA_ESTANDAR		VARCHAR2(256) NOT NULL ,
 DESCRIPCION			VARCHAR2(1024) ,
 ROL_CUENTA			CHAR(1) NOT NULL ,
 ID_TIPO_CUENTA			NUMBER(12) ,
 NATURALEZA			CHAR(1) ,
 FECHA_INICIO			DATE NOT NULL ,
 FECHA_FIN			DATE NOT NULL
);


CREATE TABLE COF_MAYOR_AUXILIAR
(
 ID_MAYOR_AUXILIAR		NUMBER(12) PRIMARY KEY , 
 ID_MAYOR			NUMBER(12) NOT NULL , 
 ID_TIPO_MAYOR_AUXILIAR		NUMBER(12) NOT NULL , 
 NOMBRE_MAYOR_AUXILIAR  	VARCHAR2(512) NOT NULL , 
 DESCRIPCION			VARCHAR2(1024) , 
 ELIMINADO			NUMBER(1) NOT NULL
);

CREATE TABLE COF_CUENTA_AUXILIAR
(
 ID_CUENTA_AUXILIAR		NUMBER(12) PRIMARY KEY , 
 ID_MAYOR_AUXILIAR		NUMBER(12) NOT NULL , 
 NUMERO_CUENTA_AUXILIAR		VARCHAR2(64) NOT NULL , 
 NOMBRE_CUENTA_AUXILIAR		VARCHAR2(256) , 
 DESCRIPCION			VARCHAR2(1024) , 
 ELIMINADA			NUMBER(1) NOT NULL
);

CREATE TABLE COF_CUENTA_AUXILIAR_ATTRS
(
 Id_Cuenta_Auxiliar_Attr	NUMBER(12) PRIMARY KEY ,
 Id_cuenta_Auxiliar		NUMBER(12) NOT NULL ,
 EntityAttrDefId 		NUMBER(12) NOT NULL ,
 ValString			VARCHAR2(2048) ,
 ValNumeric			NUMBER ,
 ValDate			DATE ,
 FromDate			DATE NOT NULL,
 ToDate				DATE NOT NULL
);

CREATE TABLE COF_SECTOR
(
 ID_SECTOR			NUMBER(12) PRIMARY KEY ,
 NOMBRE_SECTOR			VARCHAR2(64) NOT NULL ,
 CLAVE_SECTOR			VARCHAR2(3) ,
 DESCRIPCION			VARCHAR2(512) ,
 ELIMINADO			NUMBER(1) NOT NULL
);

CREATE TABLE COF_MAPEO_AREA
(
 ID_CUENTA_ESTANDAR		NUMBER(12) NOT NULL ,
 PATRON_AREA			VARCHAR(6) NOT NULL ,
 FECHA_INICIO			DATE NOT NULL ,
 FECHA_FIN			DATE NOT NULL
);

CREATE TABLE COF_MAPEO_SECTOR
(
 ID_CUENTA_ESTANDAR		NUMBER(12) NOT NULL ,
 ID_SECTOR			NUMBER(12) NOT NULL ,
 ROL_SECTOR			CHAR(1) NOT NULL ,
 FECHA_INICIO			DATE NOT NULL ,
 FECHA_FIN			DATE NOT NULL
);

CREATE TABLE COF_MAPEO_MONEDA
(
 ID_CUENTA_ESTANDAR		NUMBER(12) NOT NULL , 
 ID_MONEDA			NUMBER(12) NOT NULL ,
 FECHA_INICIO			DATE NOT NULL ,
 FECHA_FIN			DATE NOT NULL
);

CREATE TABLE COF_MAPEO_MAYOR_AUXILIAR
(
 ID_MAYOR_AUXILIAR		NUMBER(12) NOT NULL ,
 ID_CUENTA			NUMBER(12) NOT NULL ,
 ID_SECTOR			NUMBER(12) 
);

CREATE TABLE COF_GRUPO_MAYOR
(
 ID_GRUPO_MAYOR			NUMBER(12) PRIMARY KEY ,
 CLIP_GRUPO_MAYOR		NUMBER(3) NOT NULL ,
 ID_TIPO_CUENTAS_STD		NUMBER(12) NOT NULL ,
 NOMBRE_GRUPO_MAYOR		VARCHAR2(256) ,
 DESCRIPCION			VARCHAR2(1024) ,
 ID_GRUPO_MAYOR_PADRE		NUMBER(12) NOT NULL ,
 ORDEN_PRESENTACION		NUMBER(12) ,
 ELIMINADO			NUMBER(1) NOT NULL ,
 FECHA_INICIO			DATE NOT NULL ,
 FECHA_FIN			DATE NOT NULL
);

CREATE TABLE COF_ELEMENTO_GRUPO_MAYOR
(
 ID_ELEMENTO_GRUPO_MAYOR	NUMBER(12) PRIMARY KEY ,
 ID_GRUPO_MAYOR			NUMBER(12) NOT NULL ,
 ID_MAYOR			NUMBER(12) NOT NULL ,
 FECHA_INICIO			DATE NOT NULL ,
 FECHA_FIN			DATE NOT NULL
);

CREATE TABLE COF_REGLA_CONTABLE (
 ID_REGLA_CONTABLE		NUMBER(12) PRIMARY KEY ,
 NOMBRE_REGLA_CONTABLE		VARCHAR2(256) NOT NULL ,
 DESCRIPCION			VARCHAR2(1024) ,
 ID_OBJETO			NUMBER(12) NOT NULL ,
 ID_OPERACION			NUMBER(12) NOT NULL ,
 TIPO_REGLA			NUMBER(1) NOT NULL ,
 ID_TIPO_CUENTAS_STD		NUMBER(12) NOT NULL ,
 ID_MAYOR_DESTINO		NUMBER(12) NOT NULL ,
 VERSION_REGLA			NUMBER(4) NOT NULL ,
 ID_METODO			NUMBER(12) NOT NULL ,
 ID_RESPONSABLE			NUMBER(12) NOT NULL ,
 ID_REGLA_CONTABLE_RAIZ		NUMBER(12) NOT NULL ,
 FECHA_INICIO			DATE NOT NULL ,
 FECHA_FIN			DATE NOT NULL
);

CREATE TABLE COF_GRUPO_CUENTA 
(
 ID_GRUPO_CUENTA		NUMBER(12) PRIMARY KEY , 
 ID_REGLA_CONTABLE		NUMBER(12) , 
 TIPO_GRUPO_CUENTA		NUMBER(2) , 
 NUMERO_GRUPO_CUENTA		VARCHAR2(16) , 
 NOMBRE_GRUPO_CUENTA		VARCHAR2(512) , 
 ID_ENTIDAD_AGRUPADOR		NUMBER(12), 
 ID_AGRUPADOR_ORIGEN		NUMBER(12), 
 CUENTA_ORIGEN_INICIAL		VARCHAR2(256) , 
 CUENTA_ORIGEN_FINAL		VARCHAR2(256) , 
 FILTRO_CUENTAS_ORIGEN		VARCHAR2(1024) , 
 AUXILIAR_ORIGEN		VARCHAR2(256) , 
 ID_SECTOR_ORIGEN		NUMBER(12) , 
 ID_MONEDA_ORIGEN		NUMBER(12) ,
 CLIP_CUENTA_ORIGEN		NUMBER(12) ,
);

CREATE TABLE COF_GRUPO_CUENTA_BIS
(
 ID_GRUPO_CUENTA		NUMBER(12) PRIMARY KEY , 	
 ID_CUENTA_DESTINO		NUMBER(12) , 
 ID_AUXILIAR_DESTINO		NUMBER(12) , 
 ID_SECTOR_DESTINO		NUMBER(12) , 
 ID_CUENTA_DESTINO_SOBREGIRO	NUMBER(12) , 
 ID_AUXILIAR_DESTINO_SOBREGIRO	NUMBER(12) , 
 ID_SECTOR_DESTINO_SOBREGIRO	NUMBER(12) , 
 AUXILIAR_DESTINO		VARCHAR2(256) , 
 OPERADOR			CHAR(1) , 
 FACTOR				NUMBER(25,10) , 
 POSICION			NUMBER(12) , 
 NIVEL				NUMBER(2) , 
 ID_GRUPO_CUENTA_PADRE		NUMBER(12), 
 FECHA_INICIO			DATE ,
 FECHA_FIN			DATE 
);

CREATE TABLE COF_EMPRESA
(
 ID_EMPRESA			NUMBER(12) PRIMARY KEY ,
 NOMBRE_EMPRESA			VARCHAR2(512) NOT NULL ,
 RFC				VARCHAR2(15) , 
 ELIMINADA			NUMBER(1) 
);

CREATE TABLE COF_DOMICILIO
(
 ID_DOMICILIO			NUMBER(12) PRIMARY KEY ,
 CALLE				VARCHAR2(128) ,
 NUMERO_EXTERIOR		VARCHAR2(8) ,
 NUMERO_INTERIOR		VARCHAR2(8) ,
 COLONIA			VARCHAR2(64) ,
 MUNICIPIO			VARCHAR2(64) ,
 CODIGO_POSTAL			VARCHAR2(8) ,
 ESTADO				VARCHAR2(64) ,
 PAIS				VARCHAR2(64) ,
 CORREO_ELECTRONICO		VARCHAR2(128) ,
 ELIMINADO			NUMBER(1) 
);

CREATE TABLE AO_CALENDARS
(
 CALENDAR_ID			NUMBER(12) PRIMARY KEY ,
 CALENDAR_NAME			VARCHAR2(64) NOT NULL , 
 CALENDAR_YEAR			NUMBER(4) 
);


CREATE TABLE AO_HOLIDAYS
(
 HOLIDAY_ID			NUMBER(12) PRIMARY KEY ,
 CALENDAR_ID			NUMBER(12) NOT NULL ,
 HOLIDAY			DATE NOT NULL ,
 HOLIDAY_NAME			VARCHAR2(128) 
);


CREATE TABLE AO_NOT_LABOR_WEEKDAYS
(
 CALENDAR_ID			NUMBER(12) NOT NULL ,
 NOT_LABOR_WEEKDAY		NUMBER(1) NOT NULL
);


CREATE TABLE AO_PERIODS
(
 PERIOD_ID			NUMBER(12) PRIMARY KEY ,
 CALENDAR_ID			NUMBER(12) NOT NULL ,
 PERIOD_NAME			VARCHAR2(64) NOT NULL ,
 FROM_DATE			DATE NOT NULL ,
 TO_DATE			DATE NOT NULL ,
 IS_OPEN			NUMBER(1) NOT NULL
);


CREATE TABLE AO_CURRENCIES
(
 CURRENCY_ID			NUMBER(12) PRIMARY KEY ,
 CURRENCY_NAME			VARCHAR2(48) NOT NULL ,
 ABBREV				VARCHAR2(4) ,
 SYMBOL				VARCHAR2(2) ,
 REPORT_ONLY			NUMBER(1) NOT NULL ,
 EDIT_EXCHANGE_RATE		NUMBER(1) NOT NULL ,
 DELETED			NUMBER(1) NOT NULL ,
 O_ID_MONEDA			VARCHAR2(2)
);


CREATE TABLE AO_EXCHANGE_RATES
(


 EXCHANGE_RATE_ID		NUMBER(12) PRIMARY KEY , 
 EXCHANGE_RATE_TYPE_ID		NUMBER(12) NOT NULL ,
 FROM_CURRENCY_ID		NUMBER(12) NOT NULL ,
 TO_CURRENCY_ID			NUMBER(12) NOT NULL ,
 FROM_DATE			DATE NOT NULL ,
 TO_DATE			DATE NOT NULL ,
 EXCHANGE_RATE			NUMBER(25,10) NOT NULL 
);

CREATE TABLE AO_ENTITIES
(
 ENTITY_ID			NUMBER(12) PRIMARY KEY ,
 ENTITY_NAME			VARCHAR2(64) NOT NULL ,
 ENTITY_DESCRIPTION		VARCHAR2(512) , 
 ENTITY_IDENTIFICATOR		VARCHAR2(64) NOT NULL , 
 OBJECTS_TABLE			VARCHAR2(48) NOT NULL ,
 OBJECT_ID_FIELD_NAME		VARCHAR2(48) NOT NULL ,
 ENTITY_ID_FIELD_NAME		VARCHAR2(48) ,
 ATTRIBUTES_TABLE		VARCHAR2(48) ,
 OBJECT_ATTR_ID_FIELD_NAME	VARCHAR2(48) ,
 ENTITY_ATTR_ID_FIELD_NAME	VARCHAR2(48)
);


CREATE TABLE AOEntityAttrDef
(
 EntityAttrDefId		NUMBER(12) PRIMARY KEY ,
 EntityId			NUMBER(12) NOT NULL ,
 Namespace			VARCHAR2(128) NOT NULL ,
 Description			VARCHAR2(255) ,
 EasyName	     		VARCHAR2(128) ,
 DataType			NUMBER(2) NOT NULL ,
 Length				NUMBER(5) NOT NULL ,
 Format				VARCHAR2(255) ,
 DefaultValue			VARCHAR2(255) ,
 IsMultiValueSet		NUMBER(1) NOT NULL ,
 IsRequired			NUMBER(1) NOT NULL ,
 KeepCiphered			NUMBER(1) NOT NULL ,
 KeepHistory			NUMBER(1) NOT NULL ,
 ValidationRule			VARCHAR2(1024) ,
 HelpText			VARCHAR2(1024) ,
 ViewOrder			NUMBER(5) NOT NULL ,
 Enabled			NUMBER(1) NOT NULL
);


CREATE TABLE AOSetItems
(
 SetItemId			NUMBER(12) PRIMARY KEY ,
 AttrDefId			NUMBER(12) NOT NULL ,
 SetItemName			VARCHAR2(64) NOT NULL , 
 SetItemValue			CHAR(1) NOT NULL ,
 SetItemEasyName		VARCHAR2(128) , 
 SetItemDescription		VARCHAR2(512) , 
 IsDefault			NUMBER(1) NOT NULL , 
 ViewOrder			NUMBER(5) NOT NULL
);


CREATE TABLE AO_Objects
(
 OBJECT_ID			NUMBER(12) PRIMARY KEY ,
 ENTITY_ID			NUMBER(12) NOT NULL ,
 OBJECT_NAME			VARCHAR2(255) NOT NULL ,
 OBJECT_DESCRIPTION		VARCHAR2(1024) ,
 OBJECT_KEY			VARCHAR2(255) ,
 PRESENTATION_ORDER		NUMBER(5) NOT NULL ,
 DELETED			NUMBER(1) NOT NULL 
);


CREATE TABLE AOObjectAttrs
(
 ObjectAttrId			NUMBER(12) PRIMARY KEY ,
 ObjectId			NUMBER(12) NOT NULL ,
 EntityAttrDefId                NUMBER(12) NOT NULL ,
 ValString			VARCHAR2(2048) ,
 ValNumeric			NUMBER ,
 ValDate			DATE ,
 FromDate			DATE NOT NULL ,
 ToDate				DATE NOT NULL 
);


/* AOObjectsRelations y AORelationTypes están pendientes */

CREATE TABLE AOObjectsRelations
(
 ObjectRelationId		NUMBER(12) PRIMARY KEY ,
 RelationTypeId			NUMBER(12) NOT NULL ,
 ObjectAId			NUMBER(12) NOT NULL ,
 ObjectBId			NUMBER(12) NOT NULL ,
 FromDate			DATE NOT NULL ,
 ToDate				DATE NOT NULL
);



CREATE TABLE AORelationTypes
(
 RelationTypeId			NUMBER(12) PRIMARY KEY ,
 EntityAId			NUMBER(12) NOT NULL ,
 EntityBId			NUMBER(12) NOT NULL
);



/* ****************************	TABLAS TEMPORALES *************************** */

CREATE GLOBAL TEMPORARY TABLE TMP_ABONOSPERIODTBL
(
 ID_MONEDA       NUMBER(12) ,
 CUENTA		 VARCHAR2(256)  ,
 SECTOR		 NUMBER(12)  ,
 AMOUNT		 NUMBER ,
 ABONOS		 NUMBER ,
 ID_MAYOR 	 NUMBER(12)  ,
 FROM_MOVS 	 NUMBER(1)  ,
 FECHA_ULT	 DATE  
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE TMP_ABONOSTBL
(
 ID_MONEDA        NUMBER(12)  ,
 CUENTA		  VARCHAR2(256)  ,
 SECTOR		  NUMBER(12)  ,	 
 AMOUNT		  NUMBER,
 ABONOS		  NUMBER,
 FROM_MOVS 	  NUMBER(1)  ,
 ID_MAYOR 	  NUMBER(12)  	 
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE TMP_CARGOSPERIODTBL
(
 ID_MONEDA        NUMBER(12)  ,
 CUENTA		  VARCHAR2(256)  ,
 SECTOR		  NUMBER(12)  ,	 
 AMOUNT		  NUMBER,
 CARGOS		  NUMBER,
 ID_MAYOR 	  NUMBER(12)  ,	 
 FROM_MOVS 	  NUMBER(1)  ,
 FECHA_ULT	  DATE  
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE TMP_CARGOSTBL
(
 ID_MONEDA        NUMBER(12)  ,
 CUENTA		  VARCHAR2(256)  ,
 SECTOR		  NUMBER(12)  ,	 
 AMOUNT		  NUMBER,
 CARGOS		  NUMBER,
 FROM_MOVS 	  NUMBER(1)  ,
 ID_MAYOR 	  NUMBER(12)
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE TMP_MOVSTBL
(
 ID_CUENTA	          NUMBER(12)  ,	 
 ID_SECTOR	          NUMBER(12)  ,	 
 ID_CUENTA_AUXILIAR       NUMBER(12)  ,	 
 TIPO_MOVIMIENTO          CHAR(1)  ,	 
 ID_MONEDA                NUMBER(12)  ,	 
 MONTO                    NUMBER(25,10)  ,	 
 MONTO_MONEDA_BASE        NUMBER(25,10)  ,	 
 SALDO_INICIAL		  NUMBER,
 FECHA_SALDO_INICIAL	  DATE,
 ID_MAYOR                 NUMBER(12)  ,	 
 FECHA_AFECTACION         DATE  ,
 NUMERO_TRANSACCION       VARCHAR2(16) ,
 FROM_MOVS 	 	  NUMBER(1)  ,
 CONCEPTO_TRANSACCION     VARCHAR2(1024)
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE TMP_SALDOSINICIALESTBL
(
 ID_MONEDA		  NUMBER,
 NATURALEZA		  CHAR(1),
 CUENTA			  VARCHAR2(256),
 SECTOR 		  NUMBER,
 SI			  NUMBER,
 SA 	                  NUMBER,
 AMOUNT_SI 		  NUMBER,
 AMOUNT			  NUMBER,
 ID_MAYOR		  NUMBER(12)  ,
 AUX			  NUMBER,	
 FROM_MOVS 	 	  NUMBER(1)  ,
 FECHA_ULT		  DATE
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE TMP_SI_TBL
(
 ID_MONEDA	          NUMBER(12)  ,
 CUENTA			  VARCHAR2(256)  ,
 SECTOR			  NUMBER(12)  ,
 AMOUNT                   NUMBER,
 SI			  NUMBER,
 FROM_MOVS 		  NUMBER(1)  ,
 ID_MAYOR		  NUMBER(12)  
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE TMP_TOTABONOSSUMPERTBL
(
 ID_MONEDA	          NUMBER(12)  ,
 CUENTA			  VARCHAR2(256)  ,
 SECTOR			  NUMBER(12)  ,
 AUX			  NUMBER(12)  ,
 FECHA_ULT		  DATE  ,
 NUMERO_TRANSACCION	  VARCHAR2(16) ,
 CONCEPTO_TRANSACCION     VARCHAR2(1024) ,
 AMOUNT                   NUMBER,
 ABONOS 		  NUMBER,
 FROM_MOVS 	          NUMBER(1)  , 
 ID_MAYOR		  NUMBER(12)  
) ON COMMIT PRESERVE ROWS; 


CREATE GLOBAL TEMPORARY TABLE TMP_TOTABONOSTBL
(
 ID_MONEDA	          NUMBER(12)  ,
 CUENTA			  VARCHAR2(256)  ,
 SECTOR			  NUMBER(12)  ,
 AUX			  NUMBER(12)  ,
 FECHA_ULT		  DATE,
 AMOUNT                   NUMBER,
 ABONOS 		  NUMBER,
 FROM_MOVS         	  NUMBER(1)  ,
 ID_MAYOR		  NUMBER
) ON COMMIT PRESERVE ROWS; 


CREATE GLOBAL TEMPORARY TABLE TMP_TOTCARGOSSUMPERTBL
(
 ID_MONEDA	          NUMBER(12)  ,
 CUENTA			  VARCHAR2(256)  ,
 SECTOR			  NUMBER(12)  ,
 AUX			  NUMBER(12)  ,
 FECHA_ULT		  DATE  ,
 NUMERO_TRANSACCION	  VARCHAR2(16) ,
 CONCEPTO_TRANSACCION     VARCHAR2(1024) ,
 AMOUNT                   NUMBER,
 CARGOS 		  NUMBER,	
 FROM_MOVS      	  NUMBER(1)  ,
 ID_MAYOR		  NUMBER
) ON COMMIT PRESERVE ROWS; 


CREATE GLOBAL TEMPORARY TABLE TMP_TOTCARGOSTBL
(
 ID_MONEDA	          NUMBER(12)  ,
 CUENTA			  VARCHAR2(256)  ,
 SECTOR			  NUMBER(12)  ,
 AUX			  NUMBER(12)  ,
 FECHA_ULT		  DATE,
 AMOUNT                   NUMBER,
 CARGOS 		  NUMBER,	
 FROM_MOVS 	 	  NUMBER(1)  ,
 ID_MAYOR		  NUMBER
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE TMP_TOTSI_TBL
(
 ID_MONEDA	          NUMBER(12)  ,
 CUENTA			  VARCHAR2(256)  ,
 SECTOR			  NUMBER(12)  ,
 AUX			  NUMBER(12)  ,
 FECHA_ULT		  DATE,
 AMOUNT                   NUMBER,
 SI      		  NUMBER,	
 FROM_MOVS 	 	  NUMBER(1)  ,
 ID_MAYOR		  NUMBER
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE TMP_SALDOS
(
 ID_MONEDA        		NUMBER(12)  ,
 NUMERO_CUENTA_ESTANDAR		VARCHAR2(256)  ,
 ID_SECTOR		  	NUMBER(12)  ,	  
 ID_CUENTA_AUXILIAR		NUMBER(12)  ,
 SALDO_INICIAL			NUMBER,
 CARGOS		  		NUMBER,
 ABONOS		  		NUMBER,
 SALDO_ACTUAL	  		NUMBER
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE TMP_SALDOS_EXT
(
 ID_MONEDA        		NUMBER(12)  ,
 NUMERO_CUENTA_ESTANDAR	  	VARCHAR2(256)  ,
 ID_SECTOR	  		NUMBER(12)  ,	  
 ID_CUENTA_AUXILIAR  		NUMBER(12)  ,
 SALDO_INICIAL	  		NUMBER,
 CARGOS		  		NUMBER,
 ABONOS		  		NUMBER,
 SALDO_ACTUAL	  		NUMBER,
 SALDO_INICIAL_MONEDA_BASE	NUMBER,
 CARGOS_MONEDA_BASE  		NUMBER,
 ABONOS_MONEDA_BASE  		NUMBER,
 SALDO_ACTUAL_MONEDA_BASE	NUMBER
) ON COMMIT PRESERVE ROWS;


CREATE TABLE ZSALDOS
(
 EMPRESA        		NUMBER(12) ,
 MAYOR				VARCHAR2(4) ,
 SECCION			VARCHAR2(4) ,
 MONEDA				VARCHAR2(2) ,
 CUENTA				VARCHAR2(22) ,
 SECTOR				VARCHAR2(2) ,
 AUXILIAR			VARCHAR2(20) ,
 SALDO_INICIAL			NUMBER ,
 CARGOS				NUMBER ,
 ABONOS				NUMBER ,
 SALDO_ACTUAL			NUMBER
) ;
