CREATE SEQUENCE SEC_ID_TRANSACCION
INCREMENT BY 1
START WITH  151189
NOCACHE;

CREATE SEQUENCE SEC_ID_MOVIMIENTO_TMP
INCREMENT BY 1
START WITH 903051
NOCACHE;

CREATE SEQUENCE SEC_ID_SALDO_INICIAL
INCREMENT BY 1
START WITH 75000
NOCACHE;

CREATE SEQUENCE SEC_ID_MAYOR
INCREMENT BY 1
START WITH 321
NOCACHE;

CREATE SEQUENCE SEC_ID_CUENTA_ESTANDAR
INCREMENT BY 1
START WITH  10320
NOCACHE;

CREATE SEQUENCE SEC_ID_CUENTA_ESTANDAR_HIST
INCREMENT BY 1
START WITH  5889
NOCACHE;

CREATE SEQUENCE SEC_ID_CUENTA
INCREMENT BY 1
START WITH 500000
NOCACHE;

CREATE SEQUENCE SEC_ID_CUENTA_HIST
INCREMENT BY 1
START WITH 500000
NOCACHE;

CREATE SEQUENCE SEC_ID_MAYOR_AUXILIAR
INCREMENT BY 1
START WITH 737
NOCACHE; 

CREATE SEQUENCE SEC_ID_CUENTA_AUXILIAR
INCREMENT BY 1
START WITH 100000
NOCACHE;

CREATE SEQUENCE SEC_ID_ATTR_CUENTA_AUXILIAR
INCREMENT BY 1
START WITH 1000000
NOCACHE;

CREATE SEQUENCE SEC_ID_SECTOR
INCREMENT BY 1
START WITH 15
NOCACHE;

CREATE SEQUENCE SEC_ID_GRUPO_MAYOR
INCREMENT BY 1
START WITH 26
NOCACHE;

CREATE SEQUENCE SEC_ID_ELEMENTO_GRUPO_MAYOR
INCREMENT BY 1
START WITH 641
NOCACHE;

CREATE SEQUENCE SEC_ID_REGLA_CONTABLE
INCREMENT BY 1
START WITH 14
NOCACHE;

CREATE SEQUENCE SEC_ID_GRUPO_CUENTA
INCREMENT BY 1
START WITH 17210
NOCACHE;

CREATE SEQUENCE SEC_ID_EMPRESA
INCREMENT BY 1
START WITH 2
NOCACHE;

CREATE SEQUENCE SEC_ID_DOMICILIO
INCREMENT BY 1
START WITH 2
NOCACHE;

CREATE SEQUENCE SEC_CALENDAR_ID
INCREMENT BY 1
START WITH 2
NOCACHE;

CREATE SEQUENCE SEC_HOLIDAY_ID
INCREMENT BY 1
START WITH 9
NOCACHE;

CREATE SEQUENCE SEC_PERIOD_ID
INCREMENT BY 1
START WITH 6
NOCACHE;

CREATE SEQUENCE SEC_CURRENCY_ID
INCREMENT BY 1
START WITH 31
NOCACHE;

CREATE SEQUENCE SEC_EXCHANGE_RATE_ID
INCREMENT BY 1
START WITH 5000
NOCACHE;

CREATE SEQUENCE SEC_ENTITY_ID
INCREMENT BY 1
START WITH 100
NOCACHE;

CREATE SEQUENCE SEC_ENTITY_ATTRIBUTE_ID
INCREMENT BY 1
START WITH 1000
NOCACHE;

CREATE SEQUENCE SEC_ENTITY_ATTR_DEF_ID
INCREMENT BY 1
START WITH 1000
NOCACHE;

CREATE SEQUENCE SEC_ATTR_DEF_ID
INCREMENT BY 1
START WITH 1000
NOCACHE;

CREATE SEQUENCE SEC_SET_ITEM_ID
INCREMENT BY 1
START WITH 1000
NOCACHE;

CREATE SEQUENCE SEC_OBJECT_ID 
INCREMENT BY 1
START WITH 1000
NOCACHE;

CREATE SEQUENCE SEC_NODE_ID 
INCREMENT BY 1
START WITH 1000
NOCACHE;

